#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_packethost="0.0.1"
  jq -n --arg packethost "$ver_packethost" '{packethost: $packethost}'
}

version "$@"
